version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: cardflow-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=cardflow

volumes:
  mongodb_data:
