version: '3'

services:
  # MongoDB service
  mongodb:
    image: mongo:4.4
    container_name: cardflow-mongodb-dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - cardflow-network-dev
    restart: unless-stopped

  # Backend service (development mode)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: cardflow-backend-dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/cardflow
      - JWT_SECRET=dev_secret_key
      - JWT_EXPIRES_IN=7d
    networks:
      - cardflow-network-dev
    restart: unless-stopped
    command: npm run dev

  # Frontend service (development mode)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: cardflow-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - cardflow-network-dev
    restart: unless-stopped
    command: npm start

# Networks
networks:
  cardflow-network-dev:
    driver: bridge

# Volumes
volumes:
  mongodb_data_dev:
